SELECT * FROM uniuyo.student;
SELECT CGPA FROM STUDENT;
SELECT NAME,Age,CGPA FROM STUDENT;
select * FROM STUDENT 
LIMIT 5;
SELECT * FROM STUDENT 
LIMIT 22;
SELECT * FROM STUDENT
ORDER BY NAME ASC;
SELECT * FROM STUDENT
ORDER BY NAME DESC;
SELECT * FROM STUDENT 
WHERE NAME = 'Edidiong Asuquo'; 
select * from student 
where year_admitted > '2015-01-13' and CGPA > 3.50; 
select * from student 
where age > 18 and CGPA < 2.50;
SELECT * FROM STUDENT 
WHERE NAME = 'Edidiong Asuquo'; 
SELECT * FROM STUDENT
WHERE AGE > 24;
SELECT * FROM STUDENT 
WHERE YEAR_ADMITTED > '2015-01-01';

